{
  "services": [
    {
      "type": "static",
      "name": "shopmate-frontend",
      "buildCommand": "npm install && npm run build",
      "staticPublishPath": "./build",
      "envVars": [
        {
          "key": "REACT_APP_API_URL",
          "scope": "build"
        }
      ]
    }
  ]
}
